Feat: Add Dockerfile & make image
xpev-infra/openldap_exporter pull request #1
Opened 2022-05-16 07:56 UTC by ischenxin

新增Dockerfile ，方便容器化部署exporter

2022-05-20 10:33 UTC, Gallardot requested changes
REST LGTM

2022-05-20 10:33 UTC, Gallardot commented on Dockerfile
> +COPY --from=binary_builder /src/target/openldap_exporter  /usr/local/bin/openldap_exporter
最后添加一个空行

2022-05-20 10:33 UTC, Gallardot commented on Makefile
> +	docker build -t openldap-exporter:1.0.0 .
最后添加一个空行

2022-05-23 01:54 UTC, ischenxin commented on Makefile
> +	docker build -t openldap-exporter:1.0.0 .
已添加

2022-05-23 01:54 UTC, ischenxin commented on Dockerfile
> +COPY --from=binary_builder /src/target/openldap_exporter  /usr/local/bin/openldap_exporter
已添加

2022-05-24 03:50 UTC, merged